from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PROPOSAL = ROOT / 'doc' / 'doc_proposal' / 'phase123_first_exploration_goal_dispatch_design.md'
REPORT = ROOT / 'doc' / 'doc_report' / 'phase123_first_exploration_goal_dispatch_design_report.md'


def _text(path: Path) -> str:
    assert path.exists(), f'missing required Phase123 document: {path}'
    return path.read_text(encoding='utf-8')


def test_phase123_proposal_is_doc_only_design_only_and_no_runtime():
    text = _text(PROPOSAL)
    required = [
        'Phase123',
        'DESIGN_ONLY',
        'doc-only/design-only',
        'do not launch Gazebo/RViz/Nav2 runtime',
        'do not send NavigateToPose goal',
        'do not start maze_explorer',
        'do not tune Nav2/MPPI/controller/config',
        'do not change exploration strategy',
        'do not change branch scoring',
        'do not change centerline gate',
        'do not change fallback',
        'do not change terminal acceptance',
        'do not claim autonomous exploration success',
        'do not claim exit success',
        'Phase124 not entered',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_phase124_preconditions_extend_phase122_handoff_ready():
    text = _text(PROPOSAL)
    required = [
        'Phase120 ingress succeeded',
        'Phase122 handoff_allowed=true',
        'Nav2 idle',
        'scan/TF/costmap fresh',
        'ingress_goal_result.result_status_label=SUCCEEDED',
        'maze_explorer_started=true',
        'maze_explorer_max_goals=0',
        'exploration_goal_dispatched=false',
        'goal_event_count=0',
        'dispatch_event_count=0',
        'goal_active=false',
        'HANDOFF_NOT_READY_NO_EXPLORATION',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_phase124_allows_only_one_current_algorithm_first_explore_goal():
    text = _text(PROPOSAL)
    required = [
        'max_goals=1',
        'first exploration goal only',
        'generated by the current maze_explorer algorithm',
        'do not manually specify Goal1',
        'not a hand-authored pose',
        'not fallback goal',
        'not terminal goal',
        'not exit goal',
        'goal_kind=explore',
        'stop immediately after first terminal outcome',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_first_goal_artifact_schema_is_explicit():
    text = _text(PROPOSAL)
    required = [
        'first_goal_artifact',
        'first_goal.candidate',
        'first_goal.pose',
        'first_goal.frame_id',
        'first_goal.selection_reason',
        'first_goal.frontier_evidence',
        'first_goal.topology_evidence',
        'first_goal.dispatch_wall_time_sec',
        'first_goal.accepted',
        'first_goal.result_status_label',
        'first_goal.abort_text',
        'first_goal.timeout',
        'Nav2 feedback',
        'local_costmap samples',
        'scan',
        'map',
        'odom/TF',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_classification_contract_is_complete_and_fail_closed():
    text = _text(PROPOSAL)
    required = [
        'FIRST_EXPLORATION_GOAL_DISPATCHED_ACCEPTED_STOP',
        'FIRST_EXPLORATION_GOAL_REJECTED_DIAGNOSTIC_FAIL',
        'FIRST_EXPLORATION_GOAL_TIMEOUT_DIAGNOSTIC_FAIL',
        'NO_VALID_FIRST_GOAL_FAIL_CLOSED',
        'HANDOFF_NOT_READY_NO_EXPLORATION',
        'fail-closed',
        'do not convert timeout/failure into success',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_success_boundary_is_first_goal_smoke_only():
    text = _text(PROPOSAL)
    required = [
        'first-goal smoke success only',
        'does not represent autonomous exploration success',
        'does not represent exit success',
        'does not validate Goal1 carry-over',
        'does not validate staging success',
        'does not validate full-maze exploration',
        'Phase124 stop condition',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_report_summarizes_design_only_work_and_guards():
    text = _text(REPORT)
    required = [
        'PHASE123_FIRST_EXPLORATION_GOAL_DISPATCH_DESIGN_COMPLETE_STOP_BEFORE_PHASE124',
        'No implementation was performed',
        'No Gazebo/RViz/Nav2 runtime was launched',
        'No NavigateToPose goal was sent',
        'No maze_explorer was started',
        'No Nav2/MPPI/controller/config tuning was performed',
        'No exploration strategy was changed',
        'No autonomous exploration success or exit success is claimed',
        'Phase124 not entered',
        'focused static tests',
    ]
    for phrase in required:
        assert phrase in text


def test_phase123_does_not_add_phase123_runtime_runner_or_analyzer():
    forbidden = [
        ROOT / 'tools' / 'run_phase123_first_exploration_goal_dispatch_design.py',
        ROOT / 'tools' / 'analyze_phase123_first_exploration_goal_dispatch_design.py',
    ]
    for path in forbidden:
        assert not path.exists(), f'Phase123 is doc-only; unexpected Phase123 runtime file exists: {path}'
